'use client';
import { useMemo, useState } from 'react';
import { createDefaultMusicSpec, type MusicSpec, chip } from '@/lib/schemas/musicSpec';
import { compileForTarget, qaMusicSpec, type Target } from '@/lib/music/compiler';

const targets: [Target,string][] = [['universal','Universal Prompt'],['suno','Suno Prompt'],['elevenlabs','ElevenLabs Music Prompt'],['lyria','Google Lyria/Flow Prompt'],['json','JSON MusicSpec']];
const setPath = (spec: MusicSpec, path: string, value: unknown): MusicSpec => { const next = structuredClone(spec) as any; const parts = path.split('.'); let ref = next; for (const p of parts.slice(0,-1)) ref = ref[p]; ref[parts.at(-1)!] = value; next.updatedAt = new Date().toISOString(); return next; };
function Field({ label, value, onChange, area=false, placeholder='' }: { label: string; value?: string | number; onChange: (v: string) => void; area?: boolean; placeholder?: string }) { return <label className="grid gap-2"><span className="label">{label}</span>{area ? <textarea value={value ?? ''} placeholder={placeholder} onChange={e=>onChange(e.target.value)} /> : <input value={value ?? ''} placeholder={placeholder} onChange={e=>onChange(e.target.value)} />}</label>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="glass rounded-3xl p-5"><h2 className="mb-4 flex items-center gap-2 text-sm font-black uppercase tracking-[.18em] text-cyan-200"><span className="h-2 w-2 rounded-full bg-vm-cyan shadow-[var(--vm-glow-cyan)]" />{title}</h2>{children}</section>; }
export default function Home() {
  const [spec, setSpec] = useState<MusicSpec>(() => createDefaultMusicSpec()); const [target, setTarget] = useState<Target>('universal');
  const output = useMemo(() => compileForTarget(spec, target), [spec, target]); const qa = useMemo(() => qaMusicSpec(spec), [spec]);
  const update = (path: string, value: unknown) => setSpec(s => setPath(s, path, value));
  const updateChips = (path: string) => (v: string) => update(path, chip(v));
  return <main className="mx-auto grid max-w-7xl gap-6 px-4 pb-28 pt-[calc(1rem+env(safe-area-inset-top))] md:grid-cols-[1.12fr_.88fr] md:px-6">
    <header className="md:col-span-2 glass rounded-[2rem] p-6"><p className="label text-vm-cyan">VASEY.AUDIO x VASEY/AI</p><h1 className="mt-2 text-3xl font-black tracking-tight md:text-5xl">Music Intelligence Suite</h1><p className="mt-3 max-w-3xl text-vm-muted">A mobile-first MusicSpec compiler that turns raw creative ideas into structured musical direction, QA findings, and platform-ready prompts without live paid API integrations.</p></header>
    <div className="grid gap-4">
      <Card title="Intent"><div className="grid gap-3 md:grid-cols-2"><Field label="Title" value={spec.title} onChange={v=>update('title',v)} /><label className="grid gap-2"><span className="label">Task</span><select value={spec.intent.task} onChange={e=>update('intent.task',e.target.value)}>{['create','enhance','analyze','rewrite','arrange','evaluate'].map(x=><option key={x}>{x}</option>)}</select></label><div className="md:col-span-2"><Field area label="Creative brief" value={spec.intent.description} onChange={v=>update('intent.description',v)} /></div><Field label="Mood / emotional goals" value={spec.intent.emotionalGoal.join(', ')} onChange={updateChips('intent.emotionalGoal')} /><Field label="Audience / use case" value={spec.intent.audienceOrUseCase} onChange={v=>update('intent.audienceOrUseCase',v)} /></div></Card>
      <Card title="Genre / Style"><div className="grid gap-3 md:grid-cols-2"><Field label="Primary genre" value={spec.style.primaryGenre} onChange={v=>update('style.primaryGenre',v)} /><Field label="Secondary genres" value={spec.style.secondaryGenres.join(', ')} onChange={updateChips('style.secondaryGenres')} /><Field label="Descriptive traits" value={spec.style.descriptiveStyleTraits.join(', ')} onChange={updateChips('style.descriptiveStyleTraits')} /><Field label="Regional influence" value={spec.style.culturalOrRegionalInfluence.join(', ')} onChange={updateChips('style.culturalOrRegionalInfluence')} /></div></Card>
      <Card title="BPM / Key / Mode + Chords"><div className="grid gap-3 md:grid-cols-4"><Field label="BPM" value={spec.theory.bpm ?? ''} onChange={v=>update('theory.bpm', v ? Number(v) : undefined)} /><Field label="Key" value={spec.theory.key} onChange={v=>update('theory.key',v)} /><Field label="Mode" value={spec.theory.mode} onChange={v=>update('theory.mode',v)} /><Field label="Meter" value={spec.theory.meter} onChange={v=>update('theory.meter',v)} /><div className="md:col-span-2"><Field label="Scale lock notes" value={spec.theory.scale.join(', ')} onChange={updateChips('theory.scale')} /></div><div className="md:col-span-2"><Field label="Chord progression" value={spec.theory.chordProgression.join(', ')} onChange={updateChips('theory.chordProgression')} /></div></div></Card>
      <Card title="Rhythm / Instrumentation"><div className="grid gap-3 md:grid-cols-2"><Field label="Groove" value={spec.rhythm.groove} onChange={v=>update('rhythm.groove',v)} /><Field label="Drum feel" value={spec.rhythm.drumFeel} onChange={v=>update('rhythm.drumFeel',v)} /><Field label="Drums" value={spec.instrumentation.drums.join(', ')} onChange={updateChips('instrumentation.drums')} /><Field label="Bass" value={spec.instrumentation.bass.join(', ')} onChange={updateChips('instrumentation.bass')} /><Field label="Harmony instruments" value={spec.instrumentation.harmonicInstruments.join(', ')} onChange={updateChips('instrumentation.harmonicInstruments')} /><Field label="Melodic / orchestral / synths" value={[...spec.instrumentation.melodicInstruments,...spec.instrumentation.orchestral,...spec.instrumentation.synths].join(', ')} onChange={v=>{const c=chip(v);update('instrumentation.melodicInstruments',c)}} /></div></Card>
      <Card title="Vocals / Arrangement / Production"><div className="grid gap-3 md:grid-cols-2"><Field label="Vocal layers" value={spec.instrumentation.vocals.join(', ')} onChange={updateChips('instrumentation.vocals')} /><Field label="Lyric theme" value={spec.lyrics?.theme} onChange={v=>update('lyrics.theme',v)} /><Field label="Hook concept" value={spec.lyrics?.hookConcept} onChange={v=>update('lyrics.hookConcept',v)} /><Field label="Song structure" value={spec.arrangement.songStructure.join(', ')} onChange={updateChips('arrangement.songStructure')} /><Field label="Production / mix traits" value={[...spec.production.sonicPalette,...spec.production.mixTraits].join(', ')} onChange={v=>{const c=chip(v);update('production.sonicPalette',c);update('production.mixTraits',c)}} /><Field label="Negative constraints" value={[...spec.constraints.mustAvoid,...spec.constraints.negativePrompt].join(', ')} onChange={v=>{const c=chip(v);update('constraints.mustAvoid',c);update('constraints.negativePrompt',c)}} /></div></Card>
    </div>
    <aside className="grid content-start gap-4 md:sticky md:top-4"><Card title="Target Platform"><div className="grid grid-cols-2 gap-2">{targets.map(([id,label])=><button key={id} role="tab" aria-selected={target===id} className="tab btn text-left text-sm text-vm-muted" onClick={()=>setTarget(id)}>{label}</button>)}</div></Card><Card title="Live Compiled Preview"><pre className="max-h-[44vh] overflow-auto whitespace-pre-wrap rounded-2xl border border-cyan-300/20 bg-black/45 p-4 font-mono text-sm leading-relaxed text-cyan-50">{output}</pre><button className="btn btn-primary mt-3 w-full" onClick={()=>navigator.clipboard?.writeText(output)}>Copy Output</button></Card><Card title="QA Panel">{qa.length ? <ul className="grid gap-2">{qa.map((q,i)=><li key={i} className="rounded-2xl border border-cyan-300/15 bg-black/30 p-3"><b className={q.level==='error'?'text-red-300':'text-cyan-200'}>{q.title}</b><p className="text-sm text-vm-muted">{q.detail}</p></li>)}</ul> : <p className="text-vm-muted">No critical issues detected. Prompt is ready for review.</p>}</Card></aside>
    <nav className="fixed inset-x-0 bottom-0 z-10 border-t border-cyan-300/20 bg-black/80 p-3 pb-[calc(.75rem+env(safe-area-inset-bottom))] backdrop-blur md:hidden"><button className="btn btn-primary w-full" onClick={()=>navigator.clipboard?.writeText(output)}>Compile + Copy {targets.find(t=>t[0]===target)?.[1]}</button></nav>
  </main>;
}
